name: CI/CD for NestJS

on:
  push:
    branches:
      - master  # Trigger on pushes to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          npm install

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          npm run build

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE
          npm test  # Adjust based on your test runner command

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd $GITHUB_WORKSPACE
            git pull origin main
            npm install
            npm run build
            npm install -g pm2  # Install PM2 globally if not installed
            pm2 restart all  # Adjust based on your process management needs

          # Optional inputs for advanced configurations
          # timeout: 30s  # Adjust timeout if necessary
          # command_timeout: 10m  # Adjust command execution timeout if necessary
